import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-gray-100">
          <Link href="/users/sign-in" className="mr-4">
            Login
          </Link>
          <Link href="/dev/api-docs" className="text-sm text-blue-500 hover:underline">
            API Docs
          </Link>
          <Link href="/users/register">Register</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
